### ISSUE TITLE
[EditFile] Crash while tapping near EditText boundary

### ISSUE THREAD

**Issue by jamesqo** [jamesqo/Repository#50]
```java
[0:] Java.Lang.StringIndexOutOfBoundsException: length=42; regionStart=140; regionLength=0
  --- End of managed Java.Lang.StringIndexOutOfBoundsException stack trace ---
java.lang.StringIndexOutOfBoundsException: length=42; regionStart=140; regionLength=0
	at java.lang.String.substring(String.java:1931)
	at android.widget.Editor$SuggestionsPopupWindow.highlightTextDifferences(Editor.java:3646)
	at android.widget.Editor$SuggestionsPopupWindow.updateSuggestions(Editor.java:3592)
	at android.widget.Editor$SuggestionsPopupWindow.show(Editor.java:3495)
	at android.widget.Editor.replace(Editor.java:359)
	at android.widget.Editor$3.run(Editor.java:2129)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by jamesqo** [comment]
```java
java.lang.StringIndexOutOfBoundsException: length=41; regionStart=337; regionLength=0
	at java.lang.String.substring(String.java:1931)
	at android.widget.Editor$SuggestionsPopupWindow.highlightTextDifferences(Editor.java:3646)
	at android.widget.Editor$SuggestionsPopupWindow.updateSuggestions(Editor.java:3592)
	at android.widget.Editor$SuggestionsPopupWindow.show(Editor.java:3495)
	at android.widget.Editor.replace(Editor.java:359)
	at android.widget.Editor$3.run(Editor.java:2129)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by rishan-chen** [comment]
May I ask how was this issue resolved?  We had a similar crash but we cannot reproduce and we don't know the root cause and solutions...
